version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - apimachinery
  - corev
  - crdkustomizeresource
  - crdkustomizewebhookpatch
  - crds
  - deepcopy
  - frontends
  - GOBIN
  - golangci
  - kdex
  - KMGTPE
  - kubebuilder
  - kustomizeconfig
  - LOCALBIN
  - manifestskustomizesamples
  - metav
  - kdexapp
  - kdexapps
  - kdexpagearchetype
  - kdexpagearchetypes
  - kdexpagebinding
  - kdexpagebindings
  - kdexpagefooter
  - kdexpageheader
  - kdexpageheaders
  - kdexpagenavigation
  - kdexpagenavigations
  - Navigations
  - numkMGTPE
  - pipefail
  - readlink
  - subresource
import: []
