apiVersion: kdex.dev/v1alpha1
kind: MicroFrontEndPageNavigation
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: generic-navigation
spec:
  content: |
    {{- define "menu" -}}
      <ul>
        {{- range $label, $value := . }}
          <li>
            {{- if ($value.path != "") -}}
              <a href="{{ $value.path }}">{{ $label }}</a>
            {{- else -}}
              <span>{{ $label }}</span>
            {{- end -}}
            {{- if ($value.children != nil) -}}
              {{- template "menu" $value.children -}}
            {{- end -}}
          </li>
        {{- end -}}
      </ul>
    {{- end -}}
    {{- template "menu" .Values.menuEntries -}}