apiVersion: kdex.dev/v1alpha1
kind: MicroFrontEndTranslation
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: microfrontendtranslation-sample
spec:
  hostRef:
    name: sample-host
  translations:
    - keysAndValues:
        name: Name
      lang: en
    - keysAndValues:
        name: Nom
      lang: fr
