apiVersion: kdex.dev/v1alpha1
kind: MicroFrontEndPageArchetype
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: generic-page
spec:
  content: |
    <!DOCTYPE html>
    <html lang="{{ .Lang }}">
      <head>
        {{ .Meta }}
        {{ .Title }}
        {{ .Stylesheet }}
        {{ .HeadScript }}
      </head>
      <body>
        <header>
          {{ .Header }}
        </header>
        <nav>
          {{ .Navigation["main"] }}
        </nav>
        <main>
          {{ .Content["main"] }}
        </main>
        <footer>
          {{ .Footer }}
        </footer>
        {{ .FootScript }}
      </body>
    </html>
  defaultFooterRef:
    name: generic-footer
  defaultHeaderRef:
    name: generic-header
  defaultMainNavigationRef:
    name: generic-navigation