/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// The optional struct fields below are pointers so that omitempty behaves as
// declared. That makes every read of a member a potential nil dereference: the
// selector compiles either way, so the compiler cannot flag the ones that were
// safe while the field was a value struct. These accessors give callers back
// the old read semantics — an unset field reads exactly like an empty one —
// without reintroducing the phantom key.

func TestGetOriginReadsUnsetAsEmpty(t *testing.T) {
	var unset KDexFunctionSpec
	assert.Nil(t, unset.GetOrigin().Executable)
	assert.Nil(t, unset.GetOrigin().Source)
	assert.Nil(t, unset.GetOrigin().Generator)

	set := KDexFunctionSpec{Origin: &FunctionOrigin{Executable: &Executable{Image: "img"}}}
	assert.Equal(t, "img", set.GetOrigin().Executable.Image)
}

func TestGetMetadataReadsUnsetAsEmpty(t *testing.T) {
	var unset KDexFunctionSpec
	assert.False(t, unset.GetMetadata().AutoGenerated)
	assert.Empty(t, unset.GetMetadata().Tags)

	set := KDexFunctionSpec{Metadata: &KDexFunctionMetadata{AutoGenerated: true}}
	assert.True(t, set.GetMetadata().AutoGenerated)
}

func TestGetRegistriesReadsUnsetAsEmpty(t *testing.T) {
	var unset KDexHostSpec
	assert.Empty(t, unset.GetRegistries().NpmRegistry)
	assert.Empty(t, unset.GetRegistries().ImageRegistry)

	set := KDexHostSpec{Registries: &Registries{NpmRegistry: "https://npm.example"}}
	assert.Equal(t, "https://npm.example", set.GetRegistries().NpmRegistry)
}

func TestGetJWTReadsUnsetAsEmpty(t *testing.T) {
	var unset Auth
	assert.Empty(t, unset.GetJWT().CookieName)
	assert.Empty(t, unset.GetJWT().TokenTTL)

	set := Auth{JWT: &JWT{CookieName: "auth_token"}}
	assert.Equal(t, "auth_token", set.GetJWT().CookieName)
}

func TestGetContactReadsUnsetAsEmpty(t *testing.T) {
	var unset Metadata
	assert.Empty(t, unset.GetContact().Name)
	assert.Empty(t, unset.GetContact().Email)

	set := Metadata{Contact: &ContactInfo{Name: "Ops"}}
	assert.Equal(t, "Ops", set.GetContact().Name)
}

func TestGetResourcesReadsUnsetAsEmpty(t *testing.T) {
	var unset Runtime
	assert.Empty(t, unset.GetResources().Requests)
	assert.Empty(t, unset.GetResources().Limits)
}

func TestGetWeightReadsUnsetAsZero(t *testing.T) {
	var unset NavigationHints
	weight := unset.GetWeight()
	assert.True(t, weight.IsZero())
}

// A nil receiver is reachable through the optional parent fields themselves
// (spec.navigationHints, spec.auth), so the accessors must tolerate it rather
// than trading one nil dereference for another.
func TestAccessorsTolerateNilReceiver(t *testing.T) {
	assert.NotPanics(t, func() {
		var spec *KDexFunctionSpec
		_ = spec.GetOrigin()
		_ = spec.GetMetadata()

		var host *KDexHostSpec
		_ = host.GetRegistries()

		var auth *Auth
		_ = auth.GetJWT()

		var meta *Metadata
		_ = meta.GetContact()

		var runtime *Runtime
		_ = runtime.GetResources()

		var hints *NavigationHints
		_ = hints.GetWeight()
	})
}
