/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=kdex-fn,categories=all;kdex
// +kubebuilder:subresource:status

// KDexFunction is the Schema for the kdexfunctions API.
//
// KDexFunction is a facility to express a particularly concise unit of logic that scales in isolation.
// Ideally these are utilized via a FaaS layer, but for simplicity, some scenarios are modeled by the
// Backend type using containers (native Kubernetes workloads).
//
// +kubebuilder:printcolumn:name="State",type=string,JSONPath=`.status.state`,description="The state of the function"
// +kubebuilder:printcolumn:name="Gen",type="string",JSONPath=".metadata.generation",priority=1
// +kubebuilder:printcolumn:name="Detail",type="string",JSONPath=".status.detail",priority=1
type KDexFunction struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +kubebuilder:validation:Optional
	metav1.ObjectMeta `json:"metadata,omitempty,omitzero"`

	// spec defines the desired state of KDexFunction
	// +kubebuilder:validation:Required
	Spec KDexFunctionSpec `json:"spec"`

	// status defines the observed state of KDexFunction
	// +kubebuilder:validation:Optional
	Status KDexFunctionStatus `json:"status,omitempty,omitzero"`
}

// +kubebuilder:object:root=true

// KDexFunctionList contains a list of KDexFunction
type KDexFunctionList struct {
	metav1.TypeMeta `json:",inline"`

	Items []KDexFunction `json:"items"`

	metav1.ListMeta `json:"metadata,omitempty"`
}

// KDexFunctionMetadata defines the metadata for the function.
type KDexFunctionMetadata struct {
	// AutoGenerated indicates if this CR was created by the "Sniffer" server.
	// +kubebuilder:validation:Optional
	AutoGenerated bool `json:"autoGenerated,omitempty" protobuf:"varint,4,opt,name=autoGenerated"`

	Metadata `json:",inline" protobuf:"bytes,4,req,name=metadata"`
}

// KDexFunctionSpec defines the desired state of KDexFunction
type KDexFunctionSpec struct {
	// API defines the OpenAPI contract for the function.
	// See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#path-item-object
	// See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object
	// The supported fields from 'path item object' are: summary, description, get, put, post, delete, options, head, patch, trace, parameters, and responses.
	// The field 'schemas' of type map[string]schema whose values are defined by 'schema object' is supported and can be referenced throughout operation definitions. References must be in the form "#/components/schemas/<name>".
	// +kubebuilder:validation:Required
	// +kubebuilder:pruning:PreserveUnknownFields
	API API `json:"api" protobuf:"bytes,2,req,name=api"`

	// Origin defines the origin of the function implementation.
	// +kubebuilder:validation:Optional
	Origin FunctionOrigin `json:"origin,omitempty" protobuf:"bytes,3,opt,name=origin"`

	// hostRef is a reference to the KDexHost that this translation belongs to.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self.name.size() > 0",message="hostRef.name must not be empty"
	HostRef corev1.LocalObjectReference `json:"hostRef" protobuf:"bytes,2,req,name=hostRef"`

	// Metadata defines the metadata for the function for cataloging and discovery purposes.
	// +kubebuilder:validation:Optional
	Metadata KDexFunctionMetadata `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
}

// KDexFunctionState reflects the current state of a KDexFunction.
// +kubebuilder:validation:Enum=Pending;OpenAPIValid;BuildValid;SourceAvailable;ExecutableAvailable;FunctionDeployed;Ready
type KDexFunctionState string

const (
	// 1. KDexFunctionStatePending indicates the function is pending action.
	KDexFunctionStatePending KDexFunctionState = "Pending"

	// 2. KDexFunctionStateOpenAPIValid indicates the OpenAPI spec is valid.
	KDexFunctionStateOpenAPIValid KDexFunctionState = "OpenAPIValid"

	// 3. KDexFunctionStateBuildValid indicates the build configuration is valid.
	KDexFunctionStateBuildValid KDexFunctionState = "BuildValid"

	// 4. KDexFunctionStateSourceAvailable indicates the source code is available.
	KDexFunctionStateSourceAvailable KDexFunctionState = "SourceAvailable"

	// 5. KDexFunctionStateExecutableAvailable indicates the executable container is available for provisioning.
	KDexFunctionStateExecutableAvailable KDexFunctionState = "ExecutableAvailable"

	// 6. KDexFunctionStateFunctionDeployed indicates the function has been deployed to the FaaS runtime.
	KDexFunctionStateFunctionDeployed KDexFunctionState = "FunctionDeployed"

	// 7. KDexFunctionStateReady indicates the function is ready for invocation.
	KDexFunctionStateReady KDexFunctionState = "Ready"
)

// KDexFunctionStatus defines the observed state of KDexFunction
type KDexFunctionStatus struct {
	KDexObjectStatus `json:",inline" protobuf:"bytes,1,rep,name=kdexObjectStatus"`

	// Detail is a human-readable description of the current state.
	// +kubebuilder:validation:Optional
	Detail string `json:"detail,omitempty" protobuf:"bytes,2,opt,name=detail"`

	// executable is a reference to executable artifact. In most cases this will be a Docker image. In some other cases
	// it may be an artifact native to FaaS Adaptor's target runtime.
	// STATUS=ExecutableAvailable
	// +kubebuilder:validation:Optional
	Executable *Executable `json:"executable,omitempty" protobuf:"bytes,3,opt,name=executable"`

	// generator holds the values to configure and execute the code generator.
	// STATUS=BuildValid
	// +kubebuilder:validation:Optional
	Generator *Generator `json:"generator,omitempty" protobuf:"bytes,4,opt,name=generator"`

	// OpenAPISchemaURL is the URL to the aggregated, full OpenAPI document.
	// STATUS=OpenAPIValid
	// +kubebuilder:validation:Optional
	OpenAPISchemaURL string `json:"openAPISchemaURL,omitempty" protobuf:"bytes,5,opt,name=openAPISchemaURL"`

	// State reflects the current state (e.g., Pending, OpenAPIValid, BuildValid, SourceAvailable, ExecutableAvailable, FunctionDeployed, Ready).
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=Pending;OpenAPIValid;BuildValid;SourceAvailable;ExecutableAvailable;FunctionDeployed;Ready
	// +kubebuilder:default=Pending
	State KDexFunctionState `json:"state,omitempty" protobuf:"bytes,7,opt,name=state"`

	// Source contains source information.
	// STATUS=SourceAvailable
	// +kubebuilder:validation:Optional
	Source *Source `json:"source,omitempty" protobuf:"bytes,8,opt,name=source"`

	// URL is the full, routable URL for the function. This URL may only be routable from within the network.
	// STATUS=FunctionDeployed
	// +kubebuilder:validation:Optional
	URL string `json:"url,omitempty" protobuf:"bytes,9,opt,name=url"`
}

func init() {
	SchemeBuilder.Register(&KDexFunction{}, &KDexFunctionList{})
}
