//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentEntry) DeepCopyInto(out *ContentEntry) {
	*out = *in
	if in.AppRef != nil {
		in, out := &in.AppRef, &out.AppRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentEntry.
func (in *ContentEntry) DeepCopy() *ContentEntry {
	if in == nil {
		return nil
	}
	out := new(ContentEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomElement) DeepCopyInto(out *CustomElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomElement.
func (in *CustomElement) DeepCopy() *CustomElement {
	if in == nil {
		return nil
	}
	out := new(CustomElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndApp) DeepCopyInto(out *MicroFrontEndApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndApp.
func (in *MicroFrontEndApp) DeepCopy() *MicroFrontEndApp {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndAppList) DeepCopyInto(out *MicroFrontEndAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndAppList.
func (in *MicroFrontEndAppList) DeepCopy() *MicroFrontEndAppList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndAppSpec) DeepCopyInto(out *MicroFrontEndAppSpec) {
	*out = *in
	if in.CustomElements != nil {
		in, out := &in.CustomElements, &out.CustomElements
		*out = make([]CustomElement, len(*in))
		copy(*out, *in)
	}
	in.PackageReference.DeepCopyInto(&out.PackageReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndAppSpec.
func (in *MicroFrontEndAppSpec) DeepCopy() *MicroFrontEndAppSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndAppStatus) DeepCopyInto(out *MicroFrontEndAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndAppStatus.
func (in *MicroFrontEndAppStatus) DeepCopy() *MicroFrontEndAppStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndHost) DeepCopyInto(out *MicroFrontEndHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndHost.
func (in *MicroFrontEndHost) DeepCopy() *MicroFrontEndHost {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndHostList) DeepCopyInto(out *MicroFrontEndHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndHostList.
func (in *MicroFrontEndHostList) DeepCopy() *MicroFrontEndHostList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndHostSpec) DeepCopyInto(out *MicroFrontEndHostSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndHostSpec.
func (in *MicroFrontEndHostSpec) DeepCopy() *MicroFrontEndHostSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndHostStatus) DeepCopyInto(out *MicroFrontEndHostStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndHostStatus.
func (in *MicroFrontEndHostStatus) DeepCopy() *MicroFrontEndHostStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageArchetype) DeepCopyInto(out *MicroFrontEndPageArchetype) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageArchetype.
func (in *MicroFrontEndPageArchetype) DeepCopy() *MicroFrontEndPageArchetype {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageArchetype)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageArchetype) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageArchetypeList) DeepCopyInto(out *MicroFrontEndPageArchetypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndPageArchetype, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageArchetypeList.
func (in *MicroFrontEndPageArchetypeList) DeepCopy() *MicroFrontEndPageArchetypeList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageArchetypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageArchetypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageArchetypeSpec) DeepCopyInto(out *MicroFrontEndPageArchetypeSpec) {
	*out = *in
	if in.DefaultFooterRef != nil {
		in, out := &in.DefaultFooterRef, &out.DefaultFooterRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.DefaultHeaderRef != nil {
		in, out := &in.DefaultHeaderRef, &out.DefaultHeaderRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.DefaultMainNavigationRef != nil {
		in, out := &in.DefaultMainNavigationRef, &out.DefaultMainNavigationRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ExtraNavigations != nil {
		in, out := &in.ExtraNavigations, &out.ExtraNavigations
		*out = new(map[string]corev1.LocalObjectReference)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]corev1.LocalObjectReference, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageArchetypeSpec.
func (in *MicroFrontEndPageArchetypeSpec) DeepCopy() *MicroFrontEndPageArchetypeSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageArchetypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageArchetypeStatus) DeepCopyInto(out *MicroFrontEndPageArchetypeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageArchetypeStatus.
func (in *MicroFrontEndPageArchetypeStatus) DeepCopy() *MicroFrontEndPageArchetypeStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageArchetypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageBinding) DeepCopyInto(out *MicroFrontEndPageBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageBinding.
func (in *MicroFrontEndPageBinding) DeepCopy() *MicroFrontEndPageBinding {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageBindingList) DeepCopyInto(out *MicroFrontEndPageBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndPageBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageBindingList.
func (in *MicroFrontEndPageBindingList) DeepCopy() *MicroFrontEndPageBindingList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageBindingSpec) DeepCopyInto(out *MicroFrontEndPageBindingSpec) {
	*out = *in
	if in.ContentEntries != nil {
		in, out := &in.ContentEntries, &out.ContentEntries
		*out = make([]ContentEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.HostRef = in.HostRef
	if in.OverrideFooterRef != nil {
		in, out := &in.OverrideFooterRef, &out.OverrideFooterRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.OverrideHeaderRef != nil {
		in, out := &in.OverrideHeaderRef, &out.OverrideHeaderRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.OverrideMainNavigationRef != nil {
		in, out := &in.OverrideMainNavigationRef, &out.OverrideMainNavigationRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.NavigationHints != nil {
		in, out := &in.NavigationHints, &out.NavigationHints
		*out = new(NavigationHints)
		(*in).DeepCopyInto(*out)
	}
	out.PageArchetypeRef = in.PageArchetypeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageBindingSpec.
func (in *MicroFrontEndPageBindingSpec) DeepCopy() *MicroFrontEndPageBindingSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageBindingStatus) DeepCopyInto(out *MicroFrontEndPageBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageBindingStatus.
func (in *MicroFrontEndPageBindingStatus) DeepCopy() *MicroFrontEndPageBindingStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageFooter) DeepCopyInto(out *MicroFrontEndPageFooter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageFooter.
func (in *MicroFrontEndPageFooter) DeepCopy() *MicroFrontEndPageFooter {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageFooter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageFooter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageFooterList) DeepCopyInto(out *MicroFrontEndPageFooterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndPageFooter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageFooterList.
func (in *MicroFrontEndPageFooterList) DeepCopy() *MicroFrontEndPageFooterList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageFooterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageFooterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageFooterSpec) DeepCopyInto(out *MicroFrontEndPageFooterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageFooterSpec.
func (in *MicroFrontEndPageFooterSpec) DeepCopy() *MicroFrontEndPageFooterSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageFooterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageFooterStatus) DeepCopyInto(out *MicroFrontEndPageFooterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageFooterStatus.
func (in *MicroFrontEndPageFooterStatus) DeepCopy() *MicroFrontEndPageFooterStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageFooterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageHeader) DeepCopyInto(out *MicroFrontEndPageHeader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageHeader.
func (in *MicroFrontEndPageHeader) DeepCopy() *MicroFrontEndPageHeader {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageHeader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageHeaderList) DeepCopyInto(out *MicroFrontEndPageHeaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndPageHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageHeaderList.
func (in *MicroFrontEndPageHeaderList) DeepCopy() *MicroFrontEndPageHeaderList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageHeaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageHeaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageHeaderSpec) DeepCopyInto(out *MicroFrontEndPageHeaderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageHeaderSpec.
func (in *MicroFrontEndPageHeaderSpec) DeepCopy() *MicroFrontEndPageHeaderSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageHeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageHeaderStatus) DeepCopyInto(out *MicroFrontEndPageHeaderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageHeaderStatus.
func (in *MicroFrontEndPageHeaderStatus) DeepCopy() *MicroFrontEndPageHeaderStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageHeaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageNavigation) DeepCopyInto(out *MicroFrontEndPageNavigation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageNavigation.
func (in *MicroFrontEndPageNavigation) DeepCopy() *MicroFrontEndPageNavigation {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageNavigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageNavigation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageNavigationList) DeepCopyInto(out *MicroFrontEndPageNavigationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndPageNavigation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageNavigationList.
func (in *MicroFrontEndPageNavigationList) DeepCopy() *MicroFrontEndPageNavigationList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageNavigationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndPageNavigationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageNavigationSpec) DeepCopyInto(out *MicroFrontEndPageNavigationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageNavigationSpec.
func (in *MicroFrontEndPageNavigationSpec) DeepCopy() *MicroFrontEndPageNavigationSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageNavigationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndPageNavigationStatus) DeepCopyInto(out *MicroFrontEndPageNavigationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndPageNavigationStatus.
func (in *MicroFrontEndPageNavigationStatus) DeepCopy() *MicroFrontEndPageNavigationStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndPageNavigationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndRenderPage) DeepCopyInto(out *MicroFrontEndRenderPage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndRenderPage.
func (in *MicroFrontEndRenderPage) DeepCopy() *MicroFrontEndRenderPage {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndRenderPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndRenderPage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndRenderPageList) DeepCopyInto(out *MicroFrontEndRenderPageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroFrontEndRenderPage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndRenderPageList.
func (in *MicroFrontEndRenderPageList) DeepCopy() *MicroFrontEndRenderPageList {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndRenderPageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroFrontEndRenderPageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndRenderPageSpec) DeepCopyInto(out *MicroFrontEndRenderPageSpec) {
	*out = *in
	out.HostRef = in.HostRef
	if in.NavigationHints != nil {
		in, out := &in.NavigationHints, &out.NavigationHints
		*out = new(NavigationHints)
		(*in).DeepCopyInto(*out)
	}
	in.PageComponents.DeepCopyInto(&out.PageComponents)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndRenderPageSpec.
func (in *MicroFrontEndRenderPageSpec) DeepCopy() *MicroFrontEndRenderPageSpec {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndRenderPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroFrontEndRenderPageStatus) DeepCopyInto(out *MicroFrontEndRenderPageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroFrontEndRenderPageStatus.
func (in *MicroFrontEndRenderPageStatus) DeepCopy() *MicroFrontEndRenderPageStatus {
	if in == nil {
		return nil
	}
	out := new(MicroFrontEndRenderPageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavigationHints) DeepCopyInto(out *NavigationHints) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavigationHints.
func (in *NavigationHints) DeepCopy() *NavigationHints {
	if in == nil {
		return nil
	}
	out := new(NavigationHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageReference) DeepCopyInto(out *PackageReference) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageReference.
func (in *PackageReference) DeepCopy() *PackageReference {
	if in == nil {
		return nil
	}
	out := new(PackageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageComponents) DeepCopyInto(out *PageComponents) {
	*out = *in
	if in.Contents != nil {
		in, out := &in.Contents, &out.Contents
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Navigations != nil {
		in, out := &in.Navigations, &out.Navigations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageComponents.
func (in *PageComponents) DeepCopy() *PageComponents {
	if in == nil {
		return nil
	}
	out := new(PageComponents)
	in.DeepCopyInto(out)
	return out
}
