//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentEntry) DeepCopyInto(out *ContentEntry) {
	*out = *in
	if in.AppRef != nil {
		in, out := &in.AppRef, &out.AppRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentEntry.
func (in *ContentEntry) DeepCopy() *ContentEntry {
	if in == nil {
		return nil
	}
	out := new(ContentEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomElement) DeepCopyInto(out *CustomElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomElement.
func (in *CustomElement) DeepCopy() *CustomElement {
	if in == nil {
		return nil
	}
	out := new(CustomElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexApp) DeepCopyInto(out *KDexApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexApp.
func (in *KDexApp) DeepCopy() *KDexApp {
	if in == nil {
		return nil
	}
	out := new(KDexApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexAppList) DeepCopyInto(out *KDexAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexAppList.
func (in *KDexAppList) DeepCopy() *KDexAppList {
	if in == nil {
		return nil
	}
	out := new(KDexAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexAppSpec) DeepCopyInto(out *KDexAppSpec) {
	*out = *in
	if in.CustomElements != nil {
		in, out := &in.CustomElements, &out.CustomElements
		*out = make([]CustomElement, len(*in))
		copy(*out, *in)
	}
	in.PackageReference.DeepCopyInto(&out.PackageReference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexAppSpec.
func (in *KDexAppSpec) DeepCopy() *KDexAppSpec {
	if in == nil {
		return nil
	}
	out := new(KDexAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexAppStatus) DeepCopyInto(out *KDexAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexAppStatus.
func (in *KDexAppStatus) DeepCopy() *KDexAppStatus {
	if in == nil {
		return nil
	}
	out := new(KDexAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHost) DeepCopyInto(out *KDexHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHost.
func (in *KDexHost) DeepCopy() *KDexHost {
	if in == nil {
		return nil
	}
	out := new(KDexHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostList) DeepCopyInto(out *KDexHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostList.
func (in *KDexHostList) DeepCopy() *KDexHostList {
	if in == nil {
		return nil
	}
	out := new(KDexHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostSpec) DeepCopyInto(out *KDexHostSpec) {
	*out = *in
	if in.DefaultThemeRef != nil {
		in, out := &in.DefaultThemeRef, &out.DefaultThemeRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.Routing.DeepCopyInto(&out.Routing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostSpec.
func (in *KDexHostSpec) DeepCopy() *KDexHostSpec {
	if in == nil {
		return nil
	}
	out := new(KDexHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostStatus) DeepCopyInto(out *KDexHostStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostStatus.
func (in *KDexHostStatus) DeepCopy() *KDexHostStatus {
	if in == nil {
		return nil
	}
	out := new(KDexHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetype) DeepCopyInto(out *KDexPageArchetype) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetype.
func (in *KDexPageArchetype) DeepCopy() *KDexPageArchetype {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetype)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageArchetype) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetypeList) DeepCopyInto(out *KDexPageArchetypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageArchetype, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetypeList.
func (in *KDexPageArchetypeList) DeepCopy() *KDexPageArchetypeList {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageArchetypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetypeSpec) DeepCopyInto(out *KDexPageArchetypeSpec) {
	*out = *in
	if in.DefaultFooterRef != nil {
		in, out := &in.DefaultFooterRef, &out.DefaultFooterRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.DefaultHeaderRef != nil {
		in, out := &in.DefaultHeaderRef, &out.DefaultHeaderRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.DefaultMainNavigationRef != nil {
		in, out := &in.DefaultMainNavigationRef, &out.DefaultMainNavigationRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ExtraNavigations != nil {
		in, out := &in.ExtraNavigations, &out.ExtraNavigations
		*out = make(map[string]*corev1.LocalObjectReference, len(*in))
		for key, val := range *in {
			var outVal *corev1.LocalObjectReference
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(corev1.LocalObjectReference)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.OverrideThemeRef != nil {
		in, out := &in.OverrideThemeRef, &out.OverrideThemeRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetypeSpec.
func (in *KDexPageArchetypeSpec) DeepCopy() *KDexPageArchetypeSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetypeStatus) DeepCopyInto(out *KDexPageArchetypeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetypeStatus.
func (in *KDexPageArchetypeStatus) DeepCopy() *KDexPageArchetypeStatus {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBinding) DeepCopyInto(out *KDexPageBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBinding.
func (in *KDexPageBinding) DeepCopy() *KDexPageBinding {
	if in == nil {
		return nil
	}
	out := new(KDexPageBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBindingList) DeepCopyInto(out *KDexPageBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBindingList.
func (in *KDexPageBindingList) DeepCopy() *KDexPageBindingList {
	if in == nil {
		return nil
	}
	out := new(KDexPageBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBindingSpec) DeepCopyInto(out *KDexPageBindingSpec) {
	*out = *in
	if in.ContentEntries != nil {
		in, out := &in.ContentEntries, &out.ContentEntries
		*out = make([]ContentEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.HostRef = in.HostRef
	if in.NavigationHints != nil {
		in, out := &in.NavigationHints, &out.NavigationHints
		*out = new(NavigationHints)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideFooterRef != nil {
		in, out := &in.OverrideFooterRef, &out.OverrideFooterRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.OverrideHeaderRef != nil {
		in, out := &in.OverrideHeaderRef, &out.OverrideHeaderRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.OverrideMainNavigationRef != nil {
		in, out := &in.OverrideMainNavigationRef, &out.OverrideMainNavigationRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.PageArchetypeRef = in.PageArchetypeRef
	if in.ParentPageRef != nil {
		in, out := &in.ParentPageRef, &out.ParentPageRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.Paths = in.Paths
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBindingSpec.
func (in *KDexPageBindingSpec) DeepCopy() *KDexPageBindingSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBindingStatus) DeepCopyInto(out *KDexPageBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBindingStatus.
func (in *KDexPageBindingStatus) DeepCopy() *KDexPageBindingStatus {
	if in == nil {
		return nil
	}
	out := new(KDexPageBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooter) DeepCopyInto(out *KDexPageFooter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooter.
func (in *KDexPageFooter) DeepCopy() *KDexPageFooter {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageFooter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooterList) DeepCopyInto(out *KDexPageFooterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageFooter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooterList.
func (in *KDexPageFooterList) DeepCopy() *KDexPageFooterList {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageFooterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooterSpec) DeepCopyInto(out *KDexPageFooterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooterSpec.
func (in *KDexPageFooterSpec) DeepCopy() *KDexPageFooterSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooterStatus) DeepCopyInto(out *KDexPageFooterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooterStatus.
func (in *KDexPageFooterStatus) DeepCopy() *KDexPageFooterStatus {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeader) DeepCopyInto(out *KDexPageHeader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeader.
func (in *KDexPageHeader) DeepCopy() *KDexPageHeader {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageHeader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeaderList) DeepCopyInto(out *KDexPageHeaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeaderList.
func (in *KDexPageHeaderList) DeepCopy() *KDexPageHeaderList {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageHeaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeaderSpec) DeepCopyInto(out *KDexPageHeaderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeaderSpec.
func (in *KDexPageHeaderSpec) DeepCopy() *KDexPageHeaderSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeaderStatus) DeepCopyInto(out *KDexPageHeaderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeaderStatus.
func (in *KDexPageHeaderStatus) DeepCopy() *KDexPageHeaderStatus {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigation) DeepCopyInto(out *KDexPageNavigation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigation.
func (in *KDexPageNavigation) DeepCopy() *KDexPageNavigation {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageNavigation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigationList) DeepCopyInto(out *KDexPageNavigationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageNavigation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigationList.
func (in *KDexPageNavigationList) DeepCopy() *KDexPageNavigationList {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageNavigationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigationSpec) DeepCopyInto(out *KDexPageNavigationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigationSpec.
func (in *KDexPageNavigationSpec) DeepCopy() *KDexPageNavigationSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigationStatus) DeepCopyInto(out *KDexPageNavigationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigationStatus.
func (in *KDexPageNavigationStatus) DeepCopy() *KDexPageNavigationStatus {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexRenderPage) DeepCopyInto(out *KDexRenderPage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexRenderPage.
func (in *KDexRenderPage) DeepCopy() *KDexRenderPage {
	if in == nil {
		return nil
	}
	out := new(KDexRenderPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexRenderPage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexRenderPageList) DeepCopyInto(out *KDexRenderPageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexRenderPage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexRenderPageList.
func (in *KDexRenderPageList) DeepCopy() *KDexRenderPageList {
	if in == nil {
		return nil
	}
	out := new(KDexRenderPageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexRenderPageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexRenderPageSpec) DeepCopyInto(out *KDexRenderPageSpec) {
	*out = *in
	out.HostRef = in.HostRef
	if in.NavigationHints != nil {
		in, out := &in.NavigationHints, &out.NavigationHints
		*out = new(NavigationHints)
		(*in).DeepCopyInto(*out)
	}
	in.PageComponents.DeepCopyInto(&out.PageComponents)
	if in.ParentPageRef != nil {
		in, out := &in.ParentPageRef, &out.ParentPageRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ThemeRef != nil {
		in, out := &in.ThemeRef, &out.ThemeRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.Paths = in.Paths
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexRenderPageSpec.
func (in *KDexRenderPageSpec) DeepCopy() *KDexRenderPageSpec {
	if in == nil {
		return nil
	}
	out := new(KDexRenderPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexRenderPageStatus) DeepCopyInto(out *KDexRenderPageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexRenderPageStatus.
func (in *KDexRenderPageStatus) DeepCopy() *KDexRenderPageStatus {
	if in == nil {
		return nil
	}
	out := new(KDexRenderPageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTheme) DeepCopyInto(out *KDexTheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTheme.
func (in *KDexTheme) DeepCopy() *KDexTheme {
	if in == nil {
		return nil
	}
	out := new(KDexTheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexThemeList) DeepCopyInto(out *KDexThemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexTheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexThemeList.
func (in *KDexThemeList) DeepCopy() *KDexThemeList {
	if in == nil {
		return nil
	}
	out := new(KDexThemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexThemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexThemeSpec) DeepCopyInto(out *KDexThemeSpec) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = make([]ThemeAsset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexThemeSpec.
func (in *KDexThemeSpec) DeepCopy() *KDexThemeSpec {
	if in == nil {
		return nil
	}
	out := new(KDexThemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexThemeStatus) DeepCopyInto(out *KDexThemeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexThemeStatus.
func (in *KDexThemeStatus) DeepCopy() *KDexThemeStatus {
	if in == nil {
		return nil
	}
	out := new(KDexThemeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslation) DeepCopyInto(out *KDexTranslation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslation.
func (in *KDexTranslation) DeepCopy() *KDexTranslation {
	if in == nil {
		return nil
	}
	out := new(KDexTranslation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTranslation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslationList) DeepCopyInto(out *KDexTranslationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexTranslation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslationList.
func (in *KDexTranslationList) DeepCopy() *KDexTranslationList {
	if in == nil {
		return nil
	}
	out := new(KDexTranslationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTranslationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslationSpec) DeepCopyInto(out *KDexTranslationSpec) {
	*out = *in
	out.HostRef = in.HostRef
	if in.Translations != nil {
		in, out := &in.Translations, &out.Translations
		*out = make([]Translation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslationSpec.
func (in *KDexTranslationSpec) DeepCopy() *KDexTranslationSpec {
	if in == nil {
		return nil
	}
	out := new(KDexTranslationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslationStatus) DeepCopyInto(out *KDexTranslationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslationStatus.
func (in *KDexTranslationStatus) DeepCopy() *KDexTranslationStatus {
	if in == nil {
		return nil
	}
	out := new(KDexTranslationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavigationHints) DeepCopyInto(out *NavigationHints) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavigationHints.
func (in *NavigationHints) DeepCopy() *NavigationHints {
	if in == nil {
		return nil
	}
	out := new(NavigationHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageReference) DeepCopyInto(out *PackageReference) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageReference.
func (in *PackageReference) DeepCopy() *PackageReference {
	if in == nil {
		return nil
	}
	out := new(PackageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageComponents) DeepCopyInto(out *PageComponents) {
	*out = *in
	if in.Contents != nil {
		in, out := &in.Contents, &out.Contents
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Navigations != nil {
		in, out := &in.Navigations, &out.Navigations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageComponents.
func (in *PageComponents) DeepCopy() *PageComponents {
	if in == nil {
		return nil
	}
	out := new(PageComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Paths) DeepCopyInto(out *Paths) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Paths.
func (in *Paths) DeepCopy() *Paths {
	if in == nil {
		return nil
	}
	out := new(Paths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Routing) DeepCopyInto(out *Routing) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Routing.
func (in *Routing) DeepCopy() *Routing {
	if in == nil {
		return nil
	}
	out := new(Routing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThemeAsset) DeepCopyInto(out *ThemeAsset) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThemeAsset.
func (in *ThemeAsset) DeepCopy() *ThemeAsset {
	if in == nil {
		return nil
	}
	out := new(ThemeAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Translation) DeepCopyInto(out *Translation) {
	*out = *in
	if in.KeysAndValues != nil {
		in, out := &in.KeysAndValues, &out.KeysAndValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Translation.
func (in *Translation) DeepCopy() *Translation {
	if in == nil {
		return nil
	}
	out := new(Translation)
	in.DeepCopyInto(out)
	return out
}
