//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Asset) DeepCopyInto(out *Asset) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Asset.
func (in *Asset) DeepCopy() *Asset {
	if in == nil {
		return nil
	}
	out := new(Asset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Assets) DeepCopyInto(out *Assets) {
	{
		in := &in
		*out = make(Assets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assets.
func (in Assets) DeepCopy() Assets {
	if in == nil {
		return nil
	}
	out := new(Assets)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionStatuses) DeepCopyInto(out *ConditionStatuses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionStatuses.
func (in *ConditionStatuses) DeepCopy() *ConditionStatuses {
	if in == nil {
		return nil
	}
	out := new(ConditionStatuses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentEntry) DeepCopyInto(out *ContentEntry) {
	*out = *in
	in.ContentEntryApp.DeepCopyInto(&out.ContentEntryApp)
	out.ContentEntryStatic = in.ContentEntryStatic
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentEntry.
func (in *ContentEntry) DeepCopy() *ContentEntry {
	if in == nil {
		return nil
	}
	out := new(ContentEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentEntryApp) DeepCopyInto(out *ContentEntryApp) {
	*out = *in
	out.AppRef = in.AppRef
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentEntryApp.
func (in *ContentEntryApp) DeepCopy() *ContentEntryApp {
	if in == nil {
		return nil
	}
	out := new(ContentEntryApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentEntryStatic) DeepCopyInto(out *ContentEntryStatic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentEntryStatic.
func (in *ContentEntryStatic) DeepCopy() *ContentEntryStatic {
	if in == nil {
		return nil
	}
	out := new(ContentEntryStatic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomElement) DeepCopyInto(out *CustomElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomElement.
func (in *CustomElement) DeepCopy() *CustomElement {
	if in == nil {
		return nil
	}
	out := new(CustomElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexApp) DeepCopyInto(out *KDexApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexApp.
func (in *KDexApp) DeepCopy() *KDexApp {
	if in == nil {
		return nil
	}
	out := new(KDexApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexAppList) DeepCopyInto(out *KDexAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexAppList.
func (in *KDexAppList) DeepCopy() *KDexAppList {
	if in == nil {
		return nil
	}
	out := new(KDexAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexAppSpec) DeepCopyInto(out *KDexAppSpec) {
	*out = *in
	if in.CustomElements != nil {
		in, out := &in.CustomElements, &out.CustomElements
		*out = make([]CustomElement, len(*in))
		copy(*out, *in)
	}
	in.PackageReference.DeepCopyInto(&out.PackageReference)
	if in.Scripts != nil {
		in, out := &in.Scripts, &out.Scripts
		*out = make([]ScriptDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.WebServer.DeepCopyInto(&out.WebServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexAppSpec.
func (in *KDexAppSpec) DeepCopy() *KDexAppSpec {
	if in == nil {
		return nil
	}
	out := new(KDexAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterApp) DeepCopyInto(out *KDexClusterApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterApp.
func (in *KDexClusterApp) DeepCopy() *KDexClusterApp {
	if in == nil {
		return nil
	}
	out := new(KDexClusterApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterAppList) DeepCopyInto(out *KDexClusterAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterAppList.
func (in *KDexClusterAppList) DeepCopy() *KDexClusterAppList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageArchetype) DeepCopyInto(out *KDexClusterPageArchetype) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageArchetype.
func (in *KDexClusterPageArchetype) DeepCopy() *KDexClusterPageArchetype {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageArchetype)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageArchetype) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageArchetypeList) DeepCopyInto(out *KDexClusterPageArchetypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterPageArchetype, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageArchetypeList.
func (in *KDexClusterPageArchetypeList) DeepCopy() *KDexClusterPageArchetypeList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageArchetypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageArchetypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageFooter) DeepCopyInto(out *KDexClusterPageFooter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageFooter.
func (in *KDexClusterPageFooter) DeepCopy() *KDexClusterPageFooter {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageFooter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageFooter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageFooterList) DeepCopyInto(out *KDexClusterPageFooterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterPageFooter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageFooterList.
func (in *KDexClusterPageFooterList) DeepCopy() *KDexClusterPageFooterList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageFooterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageFooterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageHeader) DeepCopyInto(out *KDexClusterPageHeader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageHeader.
func (in *KDexClusterPageHeader) DeepCopy() *KDexClusterPageHeader {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageHeader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageHeaderList) DeepCopyInto(out *KDexClusterPageHeaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterPageHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageHeaderList.
func (in *KDexClusterPageHeaderList) DeepCopy() *KDexClusterPageHeaderList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageHeaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageHeaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageNavigation) DeepCopyInto(out *KDexClusterPageNavigation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageNavigation.
func (in *KDexClusterPageNavigation) DeepCopy() *KDexClusterPageNavigation {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageNavigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageNavigation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterPageNavigationList) DeepCopyInto(out *KDexClusterPageNavigationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterPageNavigation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterPageNavigationList.
func (in *KDexClusterPageNavigationList) DeepCopy() *KDexClusterPageNavigationList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterPageNavigationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterPageNavigationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterScriptLibrary) DeepCopyInto(out *KDexClusterScriptLibrary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterScriptLibrary.
func (in *KDexClusterScriptLibrary) DeepCopy() *KDexClusterScriptLibrary {
	if in == nil {
		return nil
	}
	out := new(KDexClusterScriptLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterScriptLibrary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterScriptLibraryList) DeepCopyInto(out *KDexClusterScriptLibraryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterScriptLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterScriptLibraryList.
func (in *KDexClusterScriptLibraryList) DeepCopy() *KDexClusterScriptLibraryList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterScriptLibraryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterScriptLibraryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterTheme) DeepCopyInto(out *KDexClusterTheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterTheme.
func (in *KDexClusterTheme) DeepCopy() *KDexClusterTheme {
	if in == nil {
		return nil
	}
	out := new(KDexClusterTheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterTheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexClusterThemeList) DeepCopyInto(out *KDexClusterThemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexClusterTheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexClusterThemeList.
func (in *KDexClusterThemeList) DeepCopy() *KDexClusterThemeList {
	if in == nil {
		return nil
	}
	out := new(KDexClusterThemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexClusterThemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHost) DeepCopyInto(out *KDexHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHost.
func (in *KDexHost) DeepCopy() *KDexHost {
	if in == nil {
		return nil
	}
	out := new(KDexHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostController) DeepCopyInto(out *KDexHostController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostController.
func (in *KDexHostController) DeepCopy() *KDexHostController {
	if in == nil {
		return nil
	}
	out := new(KDexHostController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostControllerList) DeepCopyInto(out *KDexHostControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexHostController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostControllerList.
func (in *KDexHostControllerList) DeepCopy() *KDexHostControllerList {
	if in == nil {
		return nil
	}
	out := new(KDexHostControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostControllerSpec) DeepCopyInto(out *KDexHostControllerSpec) {
	*out = *in
	in.Host.DeepCopyInto(&out.Host)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostControllerSpec.
func (in *KDexHostControllerSpec) DeepCopy() *KDexHostControllerSpec {
	if in == nil {
		return nil
	}
	out := new(KDexHostControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostList) DeepCopyInto(out *KDexHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostList.
func (in *KDexHostList) DeepCopy() *KDexHostList {
	if in == nil {
		return nil
	}
	out := new(KDexHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostPackageReferences) DeepCopyInto(out *KDexHostPackageReferences) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostPackageReferences.
func (in *KDexHostPackageReferences) DeepCopy() *KDexHostPackageReferences {
	if in == nil {
		return nil
	}
	out := new(KDexHostPackageReferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostPackageReferences) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostPackageReferencesList) DeepCopyInto(out *KDexHostPackageReferencesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexHostPackageReferences, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostPackageReferencesList.
func (in *KDexHostPackageReferencesList) DeepCopy() *KDexHostPackageReferencesList {
	if in == nil {
		return nil
	}
	out := new(KDexHostPackageReferencesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexHostPackageReferencesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostPackageReferencesSpec) DeepCopyInto(out *KDexHostPackageReferencesSpec) {
	*out = *in
	if in.PackageReferences != nil {
		in, out := &in.PackageReferences, &out.PackageReferences
		*out = make([]PackageReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostPackageReferencesSpec.
func (in *KDexHostPackageReferencesSpec) DeepCopy() *KDexHostPackageReferencesSpec {
	if in == nil {
		return nil
	}
	out := new(KDexHostPackageReferencesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexHostSpec) DeepCopyInto(out *KDexHostSpec) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = make(Assets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultThemeRef != nil {
		in, out := &in.DefaultThemeRef, &out.DefaultThemeRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	in.Routing.DeepCopyInto(&out.Routing)
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	in.WebServer.DeepCopyInto(&out.WebServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexHostSpec.
func (in *KDexHostSpec) DeepCopy() *KDexHostSpec {
	if in == nil {
		return nil
	}
	out := new(KDexHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexObject) DeepCopyInto(out *KDexObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexObject.
func (in *KDexObject) DeepCopy() *KDexObject {
	if in == nil {
		return nil
	}
	out := new(KDexObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexObjectReference) DeepCopyInto(out *KDexObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexObjectReference.
func (in *KDexObjectReference) DeepCopy() *KDexObjectReference {
	if in == nil {
		return nil
	}
	out := new(KDexObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexObjectStatus) DeepCopyInto(out *KDexObjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexObjectStatus.
func (in *KDexObjectStatus) DeepCopy() *KDexObjectStatus {
	if in == nil {
		return nil
	}
	out := new(KDexObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetype) DeepCopyInto(out *KDexPageArchetype) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetype.
func (in *KDexPageArchetype) DeepCopy() *KDexPageArchetype {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetype)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageArchetype) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetypeList) DeepCopyInto(out *KDexPageArchetypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageArchetype, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetypeList.
func (in *KDexPageArchetypeList) DeepCopy() *KDexPageArchetypeList {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageArchetypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageArchetypeSpec) DeepCopyInto(out *KDexPageArchetypeSpec) {
	*out = *in
	if in.DefaultFooterRef != nil {
		in, out := &in.DefaultFooterRef, &out.DefaultFooterRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	if in.DefaultHeaderRef != nil {
		in, out := &in.DefaultHeaderRef, &out.DefaultHeaderRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	if in.DefaultMainNavigationRef != nil {
		in, out := &in.DefaultMainNavigationRef, &out.DefaultMainNavigationRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	if in.ExtraNavigations != nil {
		in, out := &in.ExtraNavigations, &out.ExtraNavigations
		*out = make(map[string]*KDexObjectReference, len(*in))
		for key, val := range *in {
			var outVal *KDexObjectReference
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(KDexObjectReference)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageArchetypeSpec.
func (in *KDexPageArchetypeSpec) DeepCopy() *KDexPageArchetypeSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageArchetypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBinding) DeepCopyInto(out *KDexPageBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBinding.
func (in *KDexPageBinding) DeepCopy() *KDexPageBinding {
	if in == nil {
		return nil
	}
	out := new(KDexPageBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBindingList) DeepCopyInto(out *KDexPageBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBindingList.
func (in *KDexPageBindingList) DeepCopy() *KDexPageBindingList {
	if in == nil {
		return nil
	}
	out := new(KDexPageBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageBindingSpec) DeepCopyInto(out *KDexPageBindingSpec) {
	*out = *in
	if in.ContentEntries != nil {
		in, out := &in.ContentEntries, &out.ContentEntries
		*out = make([]ContentEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.HostRef = in.HostRef
	if in.NavigationHints != nil {
		in, out := &in.NavigationHints, &out.NavigationHints
		*out = new(NavigationHints)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideFooterRef != nil {
		in, out := &in.OverrideFooterRef, &out.OverrideFooterRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	if in.OverrideHeaderRef != nil {
		in, out := &in.OverrideHeaderRef, &out.OverrideHeaderRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	if in.OverrideMainNavigationRef != nil {
		in, out := &in.OverrideMainNavigationRef, &out.OverrideMainNavigationRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	out.PageArchetypeRef = in.PageArchetypeRef
	if in.ParentPageRef != nil {
		in, out := &in.ParentPageRef, &out.ParentPageRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.Paths = in.Paths
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageBindingSpec.
func (in *KDexPageBindingSpec) DeepCopy() *KDexPageBindingSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooter) DeepCopyInto(out *KDexPageFooter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooter.
func (in *KDexPageFooter) DeepCopy() *KDexPageFooter {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageFooter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooterList) DeepCopyInto(out *KDexPageFooterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageFooter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooterList.
func (in *KDexPageFooterList) DeepCopy() *KDexPageFooterList {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageFooterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageFooterSpec) DeepCopyInto(out *KDexPageFooterSpec) {
	*out = *in
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageFooterSpec.
func (in *KDexPageFooterSpec) DeepCopy() *KDexPageFooterSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageFooterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeader) DeepCopyInto(out *KDexPageHeader) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeader.
func (in *KDexPageHeader) DeepCopy() *KDexPageHeader {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageHeader) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeaderList) DeepCopyInto(out *KDexPageHeaderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeaderList.
func (in *KDexPageHeaderList) DeepCopy() *KDexPageHeaderList {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeaderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageHeaderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageHeaderSpec) DeepCopyInto(out *KDexPageHeaderSpec) {
	*out = *in
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageHeaderSpec.
func (in *KDexPageHeaderSpec) DeepCopy() *KDexPageHeaderSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageHeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigation) DeepCopyInto(out *KDexPageNavigation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigation.
func (in *KDexPageNavigation) DeepCopy() *KDexPageNavigation {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageNavigation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigationList) DeepCopyInto(out *KDexPageNavigationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexPageNavigation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigationList.
func (in *KDexPageNavigationList) DeepCopy() *KDexPageNavigationList {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexPageNavigationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexPageNavigationSpec) DeepCopyInto(out *KDexPageNavigationSpec) {
	*out = *in
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexPageNavigationSpec.
func (in *KDexPageNavigationSpec) DeepCopy() *KDexPageNavigationSpec {
	if in == nil {
		return nil
	}
	out := new(KDexPageNavigationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexScriptLibrary) DeepCopyInto(out *KDexScriptLibrary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexScriptLibrary.
func (in *KDexScriptLibrary) DeepCopy() *KDexScriptLibrary {
	if in == nil {
		return nil
	}
	out := new(KDexScriptLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexScriptLibrary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexScriptLibraryList) DeepCopyInto(out *KDexScriptLibraryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexScriptLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexScriptLibraryList.
func (in *KDexScriptLibraryList) DeepCopy() *KDexScriptLibraryList {
	if in == nil {
		return nil
	}
	out := new(KDexScriptLibraryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexScriptLibraryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexScriptLibrarySpec) DeepCopyInto(out *KDexScriptLibrarySpec) {
	*out = *in
	if in.PackageReference != nil {
		in, out := &in.PackageReference, &out.PackageReference
		*out = new(PackageReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Scripts != nil {
		in, out := &in.Scripts, &out.Scripts
		*out = make([]ScriptDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexScriptLibrarySpec.
func (in *KDexScriptLibrarySpec) DeepCopy() *KDexScriptLibrarySpec {
	if in == nil {
		return nil
	}
	out := new(KDexScriptLibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTheme) DeepCopyInto(out *KDexTheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTheme.
func (in *KDexTheme) DeepCopy() *KDexTheme {
	if in == nil {
		return nil
	}
	out := new(KDexTheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexThemeList) DeepCopyInto(out *KDexThemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexTheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexThemeList.
func (in *KDexThemeList) DeepCopy() *KDexThemeList {
	if in == nil {
		return nil
	}
	out := new(KDexThemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexThemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexThemeSpec) DeepCopyInto(out *KDexThemeSpec) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = make(Assets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScriptLibraryRef != nil {
		in, out := &in.ScriptLibraryRef, &out.ScriptLibraryRef
		*out = new(KDexObjectReference)
		**out = **in
	}
	in.WebServer.DeepCopyInto(&out.WebServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexThemeSpec.
func (in *KDexThemeSpec) DeepCopy() *KDexThemeSpec {
	if in == nil {
		return nil
	}
	out := new(KDexThemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslation) DeepCopyInto(out *KDexTranslation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslation.
func (in *KDexTranslation) DeepCopy() *KDexTranslation {
	if in == nil {
		return nil
	}
	out := new(KDexTranslation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTranslation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslationList) DeepCopyInto(out *KDexTranslationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDexTranslation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslationList.
func (in *KDexTranslationList) DeepCopy() *KDexTranslationList {
	if in == nil {
		return nil
	}
	out := new(KDexTranslationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDexTranslationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDexTranslationSpec) DeepCopyInto(out *KDexTranslationSpec) {
	*out = *in
	out.HostRef = in.HostRef
	if in.Translations != nil {
		in, out := &in.Translations, &out.Translations
		*out = make([]Translation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDexTranslationSpec.
func (in *KDexTranslationSpec) DeepCopy() *KDexTranslationSpec {
	if in == nil {
		return nil
	}
	out := new(KDexTranslationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NavigationHints) DeepCopyInto(out *NavigationHints) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NavigationHints.
func (in *NavigationHints) DeepCopy() *NavigationHints {
	if in == nil {
		return nil
	}
	out := new(NavigationHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageReference) DeepCopyInto(out *PackageReference) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageReference.
func (in *PackageReference) DeepCopy() *PackageReference {
	if in == nil {
		return nil
	}
	out := new(PackageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Paths) DeepCopyInto(out *Paths) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Paths.
func (in *Paths) DeepCopy() *Paths {
	if in == nil {
		return nil
	}
	out := new(Paths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Routing) DeepCopyInto(out *Routing) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Routing.
func (in *Routing) DeepCopy() *Routing {
	if in == nil {
		return nil
	}
	out := new(Routing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptDef) DeepCopyInto(out *ScriptDef) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptDef.
func (in *ScriptDef) DeepCopy() *ScriptDef {
	if in == nil {
		return nil
	}
	out := new(ScriptDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StyleDef) DeepCopyInto(out *StyleDef) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StyleDef.
func (in *StyleDef) DeepCopy() *StyleDef {
	if in == nil {
		return nil
	}
	out := new(StyleDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Translation) DeepCopyInto(out *Translation) {
	*out = *in
	if in.KeysAndValues != nil {
		in, out := &in.KeysAndValues, &out.KeysAndValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Translation.
func (in *Translation) DeepCopy() *Translation {
	if in == nil {
		return nil
	}
	out := new(Translation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebServer) DeepCopyInto(out *WebServer) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebServer.
func (in *WebServer) DeepCopy() *WebServer {
	if in == nil {
		return nil
	}
	out := new(WebServer)
	in.DeepCopyInto(out)
	return out
}
