//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package configuration

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthData) DeepCopyInto(out *AuthData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthData.
func (in *AuthData) DeepCopy() *AuthData {
	if in == nil {
		return nil
	}
	out := new(AuthData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendDefault) DeepCopyInto(out *BackendDefault) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.HttpRoute.DeepCopyInto(&out.HttpRoute)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendDefault.
func (in *BackendDefault) DeepCopy() *BackendDefault {
	if in == nil {
		return nil
	}
	out := new(BackendDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostDefault) DeepCopyInto(out *HostDefault) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	out.RoleRef = in.RoleRef
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostDefault.
func (in *HostDefault) DeepCopy() *HostDefault {
	if in == nil {
		return nil
	}
	out := new(HostDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusConfiguration) DeepCopyInto(out *NexusConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.BackendDefault.DeepCopyInto(&out.BackendDefault)
	out.DefaultImageRegistry = in.DefaultImageRegistry
	out.DefaultNpmRegistry = in.DefaultNpmRegistry
	in.HostDefault.DeepCopyInto(&out.HostDefault)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusConfiguration.
func (in *NexusConfiguration) DeepCopy() *NexusConfiguration {
	if in == nil {
		return nil
	}
	out := new(NexusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Registry) DeepCopyInto(out *Registry) {
	*out = *in
	out.AuthData = in.AuthData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Registry.
func (in *Registry) DeepCopy() *Registry {
	if in == nil {
		return nil
	}
	out := new(Registry)
	in.DeepCopyInto(out)
	return out
}
