//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package configuration

import (
	"k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthData) DeepCopyInto(out *AuthData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthData.
func (in *AuthData) DeepCopy() *AuthData {
	if in == nil {
		return nil
	}
	out := new(AuthData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FocusControllerConfiguration) DeepCopyInto(out *FocusControllerConfiguration) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Service.DeepCopyInto(&out.Service)
	if in.RolePolicyRules != nil {
		in, out := &in.RolePolicyRules, &out.RolePolicyRules
		*out = make([]v1.PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FocusControllerConfiguration.
func (in *FocusControllerConfiguration) DeepCopy() *FocusControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(FocusControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusConfiguration) DeepCopyInto(out *NexusConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.FocusController.DeepCopyInto(&out.FocusController)
	in.ThemeServer.DeepCopyInto(&out.ThemeServer)
	out.DefaultRegistry = in.DefaultRegistry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusConfiguration.
func (in *NexusConfiguration) DeepCopy() *NexusConfiguration {
	if in == nil {
		return nil
	}
	out := new(NexusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NexusConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfiguration) DeepCopyInto(out *RegistryConfiguration) {
	*out = *in
	out.AuthData = in.AuthData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfiguration.
func (in *RegistryConfiguration) DeepCopy() *RegistryConfiguration {
	if in == nil {
		return nil
	}
	out := new(RegistryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThemeServerConfiguration) DeepCopyInto(out *ThemeServerConfiguration) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.HttpRoute.DeepCopyInto(&out.HttpRoute)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThemeServerConfiguration.
func (in *ThemeServerConfiguration) DeepCopy() *ThemeServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ThemeServerConfiguration)
	in.DeepCopyInto(out)
	return out
}
